# Generated by Django 4.1 on 2023-03-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_price_product_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='map_url',
        ),
    ]
