# Generated by Django 4.1 on 2023-03-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_image_url_product_map_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
