# Generated by Django 4.1 on 2023-03-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='onwer',
            new_name='owner',
        ),
    ]
